spring:
  application:
    name: bluebankapi
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # localhost:{postgreSQL-port}/{database-name}
    username: postgres
    password: 1401
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: GMT+0
